language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t osvi52/docker-react -f Dockerfile.dev .
  ##- docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true osvi52/docker-react npm run test -- --coverage
